Admin/security
the-difference-engine/we-r-next-generation pull request #42
Opened 2018-05-08 00:48 UTC by spyeadon

2018-05-08 22:28 UTC, zachgarwood requested changes
See if you can [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) up this code.

2018-05-08 22:28 UTC, zachgarwood commented on app.rb
> +        halt(401, "Invalid Token in admin check")
Lines 60-62 are basically the same as lines 70-73. See if you can find a way to consolidate that functionality and eliminate duplicate code. Check out the Helpers section of the intro docs: http://sinatrarb.com/intro.html.

2018-05-10 01:21 UTC, spyeadon commented
@zachgarwood Made some changes. I did not use the helpers, but I did DRY up the if else logic in the before do so there is no redundancy

2018-05-10 23:18 UTC, zachgarwood approved these changes
Nice as ice!

2018-05-10 23:19 UTC, merged